#!/usr/bin/env bash
#
# Creates an SSH Tunnel to the specified server.

# Adds SSH options to the given array.
function ssh-global-options() {
  # Bash 4.3+ nameref https://www.gnu.org/software/bash/manual/html_node/Shell-Parameters.html
  local -n arr="$1"
  if [ -r "${config}" ]; then
    arr+=("-F" "${config}")
  fi
}

function ssh-check() {
  MYNAME="$(id -u -n)@$(uname -n)"
  ssh_options=()
  ssh-global-options ssh_options
  ssh "${ssh_options[@]}" "${destination}" 'mkdir -p ~/connections && touch ~/connections/'"${MYNAME}.test"
}

function ssh-tunnel() {
  MACHINE_ID=$(cat /var/lib/dbus/machine-id || true)
  if [ -z "$MACHINE_ID" ]; then
    mac="$(cat /sys/class/net/*/address | head -1)"
    MACHINE_ID="$(( 0x"${mac//:/''}" ))"
  fi
  SALTED_MACHINE_ID_HEX=$(
    echo "${MACHINE_ID}_nqminds-random-fixed-saltWW19bNQ5VI2xkM" | openssl dgst -hex -sha512-256 | grep -oE '[[:xdigit:]]{64}'
  )
  SALTED_MACHINE_ID=$(\
          echo "${MACHINE_ID}_nqminds-random-fixed-saltWW19bNQ5VI2xkM" \
          | openssl dgst -binary -sha512-256 | openssl base64 -A )

  # default tunnel port in 49152-65535 fixed on machine id
  PORT=$((0x$SALTED_MACHINE_ID_HEX%16383 + 49152))

  # see https://tools.ietf.org/html/rfc3548#page-6 for base64 in filenames
  SALTED_MACHINE_ID=${SALTED_MACHINE_ID//"/"/"_"}
  SALTED_MACHINE_ID=${SALTED_MACHINE_ID//"+"/"-"}
  MYNAME="$(id -u -n)@$(uname -n)"

  # keep on running ssh tunnel until we don't have a listen port failure

  # putting localhost:${PORT} means the port is only accessible from localhost.
  # putting *:${PORT}, means the port is accessible from all interfaces, ie
  # going www.server.com:8080 will connect to the client:22

  ssh_options=(
    # description of ssh flags at https://manpages.ubuntu.com/manpages/jammy/man1/ssh.1.html
    "-tt" # force tty (so that `trap` works properly to monitor the tunnel)
    "-o" "RemoteForward=localhost:${PORT} localhost:${host_port}"
  )
  ssh-global-options ssh_options

  while FNAME="${MYNAME}:${PORT}" \
    && ssh "${ssh_options[@]}" "${destination}" \
    "mkdir -p ~/connections \
    && FNAME=${FNAME} \
    && if [ -f ~/connections/\${FNAME} \
        && ! grep "Machine ID: ${SALTED_MACHINE_ID}" < ~/connections/\${FNAME}]; then \
      FNAME=${FNAME}+${SALTED_MACHINE_ID}; fi \
    && echo $( \
        DATA="${MYNAME} tunneled to localhost:${PORT} on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"; \
        DATA="${DATA}\nSalted Machine ID: ${SALTED_MACHINE_ID}"; \
        IP_A_DATA="${MYNAME}:~$ ip a \n $(ip a) \n"; \
        printf "${DATA}\n${IP_A_DATA}" | gzip | base64 -w0 \
      ) \
      | base64 -d | gunzip > ~/connections/\${FNAME} \
    && rm -f ~/connections/\${FNAME}+disconnected \
    && eval 'sleep infinity&' \
    && eval 'echo \\\$1' | read SLEEP_PID \
    && trap \"mv ~/connections/\${FNAME} \
      ~/connections/\${FNAME}+disconnected\
      && eval 'echo Disconnected at \\\$(date -u +'%Y-%m-%dT%H:%M:%SZ')'\
        >> ~/connections/\${FNAME}+disconnected\
      && kill -SIGINT \\\${SLEEP_PID} \" EXIT \
    && wait" \
  |& grep "Error: remote port forwarding failed for listen port"; do
    # RemotePortForwarding Failed!
    # Port already in use
    # Try using random ports until one works.

    # we want a port between 1024 and 65535, range of 64511 numbers
    R=$(($RANDOM%64511))
    # our random port
    PORT=$(($R+1024))
    # make sure the PORT isn't in the list of IANA registered ports
    while grep "${PORT}/tcp" /etc/services; do
      # find a new random port
      R=$(($RANDOM%64511)); PORT=$(($R+1024))
    done
  done
}

destination=nqminds-iot-hub-ssh-control
config="/etc/ssh-tunnel/ssh-tunnel.config"
host_port=22
check=0

help_text="Usage: $(basename "$0") [OPTIONS] [DESTINATION]

Creates an SSH tunnel to the specified server.

The tunnel port will be 'localhost:<port>' on the server, where
<port> is a pseudo-random port based on this machines's /etc/machine-id value.
(or random if it's not available).

While the tunnel is active, a file called '~/connections/<hostname>:<port>'
will be created on the server, containing the 'ip a' data of this
machine. You can then SSH into this machine from the server using:
'ssh <user>@localhost -p <port>'.

When the tunnel is closed, the file will be renamed to
'~/connections/<hostname>:<port>+disconnected'.

Options:
  -h, --help:        Show this help message and exit.
  -d, --destination: The destination to SSH to.
                     Defaults to nqminds-iot-hub-ssh-control
                     in your ssh_config file.
  -P, --host-port PORT    The host port to tunnel to. Defaults to port $host_port.
  --check:           Checks to see if SSH can be used to connect to the target.
                     Creates a file called '~/connections/<hostname>.test' to check
                     for permission errors.
  -c, --config:      Specify a custom ssh_config file.
                     Defaults to $config.
                     Ignored if this file doesn't exist or cannot be read.

"

showHelp() {
  echo 2>&1 "$help_text"
}

options=$(getopt -l "help,destination:,check,config:,host-port:" -o "h,d:,P:" -- "$@")
eval set -- "$options"

while [ "$1" ]; do
case $1 in
-h|--help)
    showHelp
    exit 0
    ;;
-d|--destination)
    if [ -z "$2" ]; then
      echo "Warning: Ignoring empty --destination and keeping '$destination'." >&2
    else
      destination="$2"
    fi
    shift
    ;;
-P|--host-port)
    host_port="$2"
    shift
    ;;
--check)
    check=1
    shift
    ;;
--config)
    if [ -r "$2" ]; then
      config="$2"
    else
      echo "Warning: Ignoring --config '$2' as it is not a readable file." >&2
    fi
    shift
    ;;
--)
    shift
    break;;
*) # default
    echo "Unknown option: $1" >&2
    showHelp
    exit 22
    ;;
esac
shift
done

export destination="${destination}"
export config="$config"

if [ "$check" -ne 0 ]; then
  ssh-check
  exit "$?"
fi
ssh-tunnel

echo 2>&1 "$(basename "$0") --destination ${destination} failed"
# always return failure since ssh-tunnel should never end
exit 1
